### ISSUE TITLE
Prevents user from entering password. 

### ISSUE THREAD

**Issue by lehbyte** [adblockultimate/AdBlocker-Ultimate-for-Firefox#15]
Had trouble entering my password in websites until I uninstalled this addon. Not sure if this addon is reading people's passwords.

**Comment by adblockultimate** [comment]
The extension doesn't monitor any inputs from users. Please let us know on which website this occurred, it is a false positive for an ad.

**Comment by adblockultimate** [comment]
I am closing the issue, please contact us on our website if you have more info.
