### ISSUE TITLE
Slow with spotify and audio pausing - preload.js:169:52 - CSP Problem

### ISSUE THREAD

**Issue by wellington1993** [adblockultimate/AdBlocker-Ultimate-for-Firefox#16]
Hi,

appears causing problem with audio play, parts loading in spotify web player.

`18:42:20.348 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). preload.js:169:52
`

https://gist.github.com/wellington1993/f8d0b3794af681c5e5e64b45159728cf

Thanks!

**Comment by adblockultimate** [comment]
Should be fixed with recent version
