### ISSUE TITLE
Possible slowing down with CSS or jquery?

### ISSUE THREAD

**Issue by alex-kovac** [adblockultimate/AdBlocker-Ultimate-for-Firefox#17]
Noticed that certain pages load slower when AdBlocker Ultimate is turned on. The page loads content without styling. FF Performance recording shows that jquery takes a long time to load ~6sec. In Safe mode pages load as expected. Did anyone notice the same issue?

- Firefox 71, no extensions but Adblocker Ultimate, standard theme.
- MacOS 10.13.6

**Comment by adblockultimate** [comment]
Can you please give me examples of webpages this is happening?

**Comment by alex-kovac** [comment]
Sorry, switched to another blocker since. I do realize including examples regarding this issue would have been useful to you now. Sorry for that.
