### ISSUE TITLE
No longer blocking twitch streaming ads

### ISSUE THREAD

**Issue by DrakeFS** [adblockultimate/AdBlocker-Ultimate-for-Firefox#18]
Noticed that Twitch has recently been able to stream ads

**Comment by JoVeI97** [comment]
Cannot reproduce. I had an issue a few days ago that my adblock ultimate was not active though, maybe this was the case? I had both adblock plus and adblock ultimate active at the same time and decided to just delete adblock plus. After that it worked fine. (Using firefox  78.0.1 (64-Bit))

**Comment by DrakeFS** [comment]
Nope, was active.   Even reinstalled and it was still letting the ads through.   Could be Twitch is A/B testing new ads?

**Comment by adblockultimate** [comment]
Couldn't reproduce either - might be testing new ads indeed. Will keep an eye on it.

**Comment by DrakeFS** [comment]
Looks like Twitch was testing new ads, getting preroll adds consistently now

**Comment by JoVeI97** [comment]
I am getting ads consistently now with the adblock enabled, too.
